"""empty message

Revision ID: 31af6acfb199
Revises: 
Create Date: 2019-11-29 12:52:29.661618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31af6acfb199'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applicant_form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applicant_form_email'), 'applicant_form', ['email'], unique=True)
    op.create_index(op.f('ix_applicant_form_timestamp'), 'applicant_form', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applicant_form_timestamp'), table_name='applicant_form')
    op.drop_index(op.f('ix_applicant_form_email'), table_name='applicant_form')
    op.drop_table('applicant_form')
    # ### end Alembic commands ###
