"""empty message

Revision ID: 6cf93584ab64
Revises: 89a5bdf1e212
Create Date: 2019-12-31 13:38:09.524285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cf93584ab64'
down_revision = '89a5bdf1e212'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applicant_form', sa.Column('school_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'applicant_form', 'school', ['school_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'applicant_form', type_='foreignkey')
    op.drop_column('applicant_form', 'school_id')
    # ### end Alembic commands ###
