"""empty message

Revision ID: 89a5bdf1e212
Revises: 8f515d656d55
Create Date: 2019-12-31 13:32:21.241935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89a5bdf1e212'
down_revision = '8f515d656d55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_name', sa.String(length=128), nullable=True),
    sa.Column('school_description', sa.String(length=128), nullable=True),
    sa.Column('school_type', sa.String(length=128), nullable=True),
    sa.Column('date_founded', sa.String(length=128), nullable=True),
    sa.Column('phone_number', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('address_1', sa.String(length=128), nullable=True),
    sa.Column('address_2', sa.String(length=128), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('stateprovince', sa.String(length=128), nullable=True),
    sa.Column('zipcode', sa.String(length=128), nullable=True),
    sa.Column('accrediting_organization', sa.String(length=128), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_school_email'), 'school', ['email'], unique=True)
    op.create_index(op.f('ix_school_timestamp'), 'school', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_school_timestamp'), table_name='school')
    op.drop_index(op.f('ix_school_email'), table_name='school')
    op.drop_table('school')
    # ### end Alembic commands ###
