"""empty message

Revision ID: 8f515d656d55
Revises: 31af6acfb199
Create Date: 2019-12-03 12:38:24.521838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f515d656d55'
down_revision = '31af6acfb199'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applicant_form', sa.Column('address_1', sa.String(length=128), nullable=True))
    op.add_column('applicant_form', sa.Column('address_2', sa.String(length=128), nullable=True))
    op.add_column('applicant_form', sa.Column('can_read_write_english', sa.String(length=128), nullable=True))
    op.add_column('applicant_form', sa.Column('cell_phone', sa.String(length=128), nullable=True))
    op.add_column('applicant_form', sa.Column('citizenship_country', sa.String(length=128), nullable=True))
    op.add_column('applicant_form', sa.Column('citizenship_status', sa.String(length=128), nullable=True))
    op.add_column('applicant_form', sa.Column('city', sa.String(length=128), nullable=True))
    op.add_column('applicant_form', sa.Column('convicted_offense', sa.String(length=128), nullable=True))
    op.add_column('applicant_form', sa.Column('convictions_explained', sa.String(length=128), nullable=True))
    op.add_column('applicant_form', sa.Column('current_employer', sa.String(length=128), nullable=True))
    op.add_column('applicant_form', sa.Column('current_position', sa.String(length=128), nullable=True))
    op.add_column('applicant_form', sa.Column('date_of_birth', sa.String(length=20), nullable=True))
    op.add_column('applicant_form', sa.Column('date_of_completion', sa.String(length=128), nullable=True))
    op.add_column('applicant_form', sa.Column('date_of_marriage', sa.String(length=128), nullable=True))
    op.add_column('applicant_form', sa.Column('gender', sa.String(length=20), nullable=True))
    op.add_column('applicant_form', sa.Column('high_school_attended', sa.String(length=128), nullable=True))
    op.add_column('applicant_form', sa.Column('highest_level_of_education_completed', sa.String(length=128), nullable=True))
    op.add_column('applicant_form', sa.Column('home_phone', sa.String(length=128), nullable=True))
    op.add_column('applicant_form', sa.Column('how_did_you_hear_about_us', sa.String(length=128), nullable=True))
    op.add_column('applicant_form', sa.Column('maiden_name', sa.String(length=128), nullable=True))
    op.add_column('applicant_form', sa.Column('marital_status', sa.String(length=128), nullable=True))
    op.add_column('applicant_form', sa.Column('middle_name', sa.String(length=128), nullable=True))
    op.add_column('applicant_form', sa.Column('school_1_end_date', sa.String(length=128), nullable=True))
    op.add_column('applicant_form', sa.Column('school_1_name', sa.String(length=128), nullable=True))
    op.add_column('applicant_form', sa.Column('school_1_start_date', sa.String(length=128), nullable=True))
    op.add_column('applicant_form', sa.Column('school_2_end_date', sa.String(length=128), nullable=True))
    op.add_column('applicant_form', sa.Column('school_2_name', sa.String(length=128), nullable=True))
    op.add_column('applicant_form', sa.Column('school_2_start_date', sa.String(length=128), nullable=True))
    op.add_column('applicant_form', sa.Column('school_3_end_date', sa.String(length=128), nullable=True))
    op.add_column('applicant_form', sa.Column('school_3_name', sa.String(length=128), nullable=True))
    op.add_column('applicant_form', sa.Column('school_3_start_date', sa.String(length=128), nullable=True))
    op.add_column('applicant_form', sa.Column('stateprovince', sa.String(length=128), nullable=True))
    op.add_column('applicant_form', sa.Column('zipcode', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applicant_form', 'zipcode')
    op.drop_column('applicant_form', 'stateprovince')
    op.drop_column('applicant_form', 'school_3_start_date')
    op.drop_column('applicant_form', 'school_3_name')
    op.drop_column('applicant_form', 'school_3_end_date')
    op.drop_column('applicant_form', 'school_2_start_date')
    op.drop_column('applicant_form', 'school_2_name')
    op.drop_column('applicant_form', 'school_2_end_date')
    op.drop_column('applicant_form', 'school_1_start_date')
    op.drop_column('applicant_form', 'school_1_name')
    op.drop_column('applicant_form', 'school_1_end_date')
    op.drop_column('applicant_form', 'middle_name')
    op.drop_column('applicant_form', 'marital_status')
    op.drop_column('applicant_form', 'maiden_name')
    op.drop_column('applicant_form', 'how_did_you_hear_about_us')
    op.drop_column('applicant_form', 'home_phone')
    op.drop_column('applicant_form', 'highest_level_of_education_completed')
    op.drop_column('applicant_form', 'high_school_attended')
    op.drop_column('applicant_form', 'gender')
    op.drop_column('applicant_form', 'date_of_marriage')
    op.drop_column('applicant_form', 'date_of_completion')
    op.drop_column('applicant_form', 'date_of_birth')
    op.drop_column('applicant_form', 'current_position')
    op.drop_column('applicant_form', 'current_employer')
    op.drop_column('applicant_form', 'convictions_explained')
    op.drop_column('applicant_form', 'convicted_offense')
    op.drop_column('applicant_form', 'city')
    op.drop_column('applicant_form', 'citizenship_status')
    op.drop_column('applicant_form', 'citizenship_country')
    op.drop_column('applicant_form', 'cell_phone')
    op.drop_column('applicant_form', 'can_read_write_english')
    op.drop_column('applicant_form', 'address_2')
    op.drop_column('applicant_form', 'address_1')
    # ### end Alembic commands ###
